export enum ResponseMessage {
  SUCCESS = 'SUCCESS',
  BAD_GATEWAY = 'BAD_GATEWAY',
  UN_AUTHORIZATION = 'UN_AUTHORIZATION',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
}
